### ISSUE TITLE
seascape.py ，element_wise_binary cannot be called in Python-scope

### ISSUE THREAD

**Issue by oridong** [Phonicavi/Shadertoy-taichi#1]
Exception has occurred: AssertionError
element_wise_binary cannot be called in Python-scope
  File "D:\00_ws\python\Taichi\Shadertoy-taichi\examples\seascape.py", line 23, in <module>
    SEA_WATER_COLOR = ti.Vector([0.8, 0.9, 0.6])*0.6

[Taichi] mode=release
[Taichi] version 0.6.8, supported archs: [cpu, cuda, opengl], commit 9f4fd27c, python 3.8.3

**Comment by Phonicavi** [comment]
It seems that the scope-issue has been solved by the new PR, see https://github.com/taichi-dev/taichi/pull/1184 thanks~:D BTW, temporally you may down-grade to taichi==0.6.7 for this example.

**Comment by zhehaoli1999** [comment]
Yes, after downgrading to taichi 0.6.7, now seascape.py is able to run, although the FPS is really low on my machine : (
