### ISSUE TITLE
render 函数里面嵌套的两个 for 循环太慢了

### ISSUE THREAD

**Issue by neozhaoliang** [Phonicavi/Shadertoy-taichi#2]
这些 shadertoy 例子跑起来只有 2-3 fps， 看了下代码，在 render 函数里面跑两层 for 循环逐个像素遍历渲染太慢了，这个过程可以并行吗？

**Comment by Phonicavi** [comment]
Actually the outermost for-loop in kernel function is automatically parallelized, see https://taichi.readthedocs.io/en/stable/hello.html?highlight=for%20loop#parallel-for-loops :)

**Comment by neozhaoliang** [comment]
我看到了，我之前的评论有误。其实运行时间和 glsl 是差不多的。
